export const CATALOG_IDENTITY_VERSION = 1;

export const CANONICAL_FIELDS = Object.freeze([
  Object.freeze({ id: 'life-sciences', label: '生命科学' }),
  Object.freeze({ id: 'medicine-health', label: '医学与健康' }),
  Object.freeze({ id: 'computer-science', label: '计算机科学' }),
  Object.freeze({ id: 'mathematics-statistics', label: '数学与统计' }),
  Object.freeze({ id: 'physics-astronomy', label: '物理与天文' }),
  Object.freeze({ id: 'chemistry', label: '化学' }),
  Object.freeze({ id: 'materials-science', label: '材料科学' }),
  Object.freeze({ id: 'earth-environment', label: '地球与环境' }),
  Object.freeze({ id: 'engineering-technology', label: '工程技术' }),
  Object.freeze({ id: 'agricultural-sciences', label: '农业科学' }),
  Object.freeze({ id: 'social-sciences', label: '社会科学' }),
  Object.freeze({ id: 'humanities', label: '人文' }),
  Object.freeze({ id: 'arts', label: '艺术' }),
]);

const RESOURCE_IDENTITIES = [
  {
    id: 'e7ba68ef-b584-4432-9b89-bc08120428d6',
    slug: 'seurat-sc-pipeline',
    legacyDisciplineId: 'biology',
    authorSlug: 'satija-lab',
    scope: 'discipline',
    primaryFieldId: 'life-sciences',
    fieldIds: ['life-sciences'],
  },
  {
    id: '059bb989-b87b-483c-b592-a8f6790e4ce9',
    slug: 'celltypist-annotator',
    legacyDisciplineId: 'biology',
    authorSlug: 'teichmann-lab',
    scope: 'discipline',
    primaryFieldId: 'life-sciences',
    fieldIds: ['life-sciences', 'medicine-health'],
  },
  {
    id: '655c589d-9201-4629-9f19-29971ffb5721',
    slug: 'mofa-integration',
    legacyDisciplineId: 'biology',
    authorSlug: 'embl-genomics',
    scope: 'discipline',
    primaryFieldId: 'life-sciences',
    fieldIds: ['life-sciences'],
  },
  {
    id: '2571af80-7962-4add-85fc-5d543d081611',
    slug: 'cite-seq-demux',
    legacyDisciplineId: 'biology',
    authorSlug: 'nygc',
    scope: 'discipline',
    primaryFieldId: 'life-sciences',
    fieldIds: ['life-sciences'],
  },
  {
    id: '41222d43-e291-4d8f-9125-b7c9138135d9',
    slug: 'opentargets-query',
    legacyDisciplineId: 'biology',
    authorSlug: 'embl-ebi',
    scope: 'discipline',
    primaryFieldId: 'medicine-health',
    fieldIds: ['medicine-health', 'life-sciences'],
  },
  {
    id: '38f78a9a-ba89-4efc-b6a0-e1effa88f5b0',
    slug: 'autodock-vina-runner',
    legacyDisciplineId: 'biology',
    authorSlug: 'scripps',
    scope: 'discipline',
    primaryFieldId: 'chemistry',
    fieldIds: ['chemistry', 'medicine-health'],
  },
  {
    id: '5c7265e0-f6fc-4e84-9c97-bae559e6b555',
    slug: 'alphafold-db-api',
    legacyDisciplineId: 'biology',
    authorSlug: 'deepmind',
    scope: 'discipline',
    primaryFieldId: 'life-sciences',
    fieldIds: ['life-sciences'],
  },
  {
    id: '20b78381-09d8-42e0-8358-061c01510184',
    slug: 'string-db-ppi',
    legacyDisciplineId: 'biology',
    authorSlug: 'cpr-embl',
    scope: 'discipline',
    primaryFieldId: 'life-sciences',
    fieldIds: ['life-sciences'],
  },
  {
    id: 'fabdd2f0-545b-43a0-8ca0-6c77d10f9b23',
    slug: 'pytorch-model-profiler',
    legacyDisciplineId: 'computer-science',
    authorSlug: 'meta-ai',
    scope: 'discipline',
    primaryFieldId: 'computer-science',
    fieldIds: ['computer-science'],
  },
  {
    id: 'c6ff573b-58b0-4561-b507-9594e11e8d5d',
    slug: 'hf-hub-connector',
    legacyDisciplineId: 'computer-science',
    authorSlug: 'huggingface',
    scope: 'discipline',
    primaryFieldId: 'computer-science',
    fieldIds: ['computer-science'],
  },
  {
    id: '5f044640-5a6d-4024-8c2b-4454e5ae0955',
    slug: 'qiskit-circuit-sim',
    legacyDisciplineId: 'physics',
    authorSlug: 'ibm-quantum',
    scope: 'discipline',
    primaryFieldId: 'physics-astronomy',
    fieldIds: ['physics-astronomy', 'computer-science'],
  },
  {
    id: '823f3d34-a567-404f-b4f5-e59bea04dc9b',
    slug: 'biomcp',
    legacyDisciplineId: null,
    authorSlug: 'genomoncology',
    scope: 'discipline',
    primaryFieldId: 'medicine-health',
    fieldIds: ['medicine-health', 'life-sciences'],
  },
  {
    id: '35b6ba8c-aba2-4082-b15d-7b47e7cf8157',
    slug: 'arxiv-mcp-server',
    legacyDisciplineId: null,
    authorSlug: 'blazickjp',
    scope: 'general',
    primaryFieldId: null,
    fieldIds: [],
  },
  {
    id: 'bf6cac39-c6b9-444f-a293-b60bd5622124',
    slug: 'anthropic-single-cell-rna-qc',
    legacyDisciplineId: null,
    authorSlug: 'anthropics',
    scope: 'discipline',
    primaryFieldId: 'life-sciences',
    fieldIds: ['life-sciences'],
  },
  {
    id: 'ab4c22b4-8aa3-480c-b9a7-faa69aec7f48',
    slug: 'anthropic-scvi-tools',
    legacyDisciplineId: null,
    authorSlug: 'anthropics',
    scope: 'discipline',
    primaryFieldId: 'life-sciences',
    fieldIds: ['life-sciences'],
  },
  {
    id: 'a9830988-40c2-4458-8b37-13dc5241dd21',
    slug: 'anthropic-nextflow-development',
    legacyDisciplineId: null,
    authorSlug: 'anthropics',
    scope: 'discipline',
    primaryFieldId: 'life-sciences',
    fieldIds: ['life-sciences'],
  },
  {
    id: 'e642bc25-52b2-45d7-9889-834db11273a6',
    slug: 'anthropic-instrument-data-to-allotrope',
    legacyDisciplineId: null,
    authorSlug: 'anthropics',
    scope: 'discipline',
    primaryFieldId: 'life-sciences',
    fieldIds: ['life-sciences', 'chemistry'],
  },
  {
    id: '92047eca-3d9b-44bf-a6cf-5cf70a56cd02',
    slug: 'anthropic-scientific-problem-selection',
    legacyDisciplineId: null,
    authorSlug: 'anthropics',
    scope: 'discipline',
    primaryFieldId: 'life-sciences',
    fieldIds: ['life-sciences'],
  },
  {
    id: 'ef77932b-5282-45bb-a93c-356f3d61c1b2',
    slug: 'anthropic-clinical-trial-protocol',
    legacyDisciplineId: null,
    authorSlug: 'anthropics',
    scope: 'discipline',
    primaryFieldId: 'medicine-health',
    fieldIds: ['medicine-health', 'life-sciences'],
  },
  {
    id: 'fa8a36ca-e15b-428d-a52d-6c98459368a9',
    slug: 'anthropic-pubmed-mcp',
    legacyDisciplineId: null,
    authorSlug: 'anthropics',
    scope: 'discipline',
    primaryFieldId: 'life-sciences',
    fieldIds: ['life-sciences', 'medicine-health'],
  },
  {
    id: 'd9007325-4629-4387-a3b7-0dd6c49ecb9d',
    slug: 'anthropic-biorxiv-mcp',
    legacyDisciplineId: null,
    authorSlug: 'anthropics',
    scope: 'discipline',
    primaryFieldId: 'life-sciences',
    fieldIds: ['life-sciences', 'medicine-health'],
  },
  {
    id: '8687c7f3-b62d-4379-94a8-6bc47030fa64',
    slug: 'anthropic-clinical-trials-mcp',
    legacyDisciplineId: null,
    authorSlug: 'anthropics',
    scope: 'discipline',
    primaryFieldId: 'medicine-health',
    fieldIds: ['medicine-health', 'life-sciences'],
  },
  {
    id: 'd79dbdba-de25-4fd5-a40d-2e28f1b5513d',
    slug: 'anthropic-chembl-mcp',
    legacyDisciplineId: null,
    authorSlug: 'anthropics',
    scope: 'discipline',
    primaryFieldId: 'chemistry',
    fieldIds: ['chemistry', 'medicine-health', 'life-sciences'],
  },
  {
    id: '120ff89b-7a51-452f-87ae-c18ec90f43e6',
    slug: 'anthropic-open-targets-mcp',
    legacyDisciplineId: null,
    authorSlug: 'anthropics',
    scope: 'discipline',
    primaryFieldId: 'medicine-health',
    fieldIds: ['medicine-health', 'life-sciences'],
  },
  {
    id: '1bd3a626-24dc-4bd4-9020-6fdeb11483e5',
    slug: 'anthropic-consensus-mcp',
    legacyDisciplineId: null,
    authorSlug: 'anthropics',
    scope: 'general',
    primaryFieldId: null,
    fieldIds: [],
  },
  {
    id: '09fc6eaf-b4cd-466c-846a-76179d913e9a',
    slug: 'anthropic-wiley-scholar-gateway-mcp',
    legacyDisciplineId: null,
    authorSlug: 'anthropics',
    scope: 'general',
    primaryFieldId: null,
    fieldIds: [],
  },
  {
    id: '1e43fc6f-d615-46bd-b6e4-f9d3a61cad67',
    slug: 'anthropic-synapse-mcp',
    legacyDisciplineId: null,
    authorSlug: 'anthropics',
    scope: 'discipline',
    primaryFieldId: 'life-sciences',
    fieldIds: ['life-sciences', 'medicine-health'],
  },
  {
    id: '5ba07a6f-70de-45c8-aaae-599006ff0e85',
    slug: 'anthropic-biorender-mcp',
    legacyDisciplineId: null,
    authorSlug: 'anthropics',
    scope: 'general',
    primaryFieldId: null,
    fieldIds: [],
  },
  {
    id: '37f47d32-acb3-4111-9110-55250db7fa12',
    slug: 'anthropic-owkin-mcp',
    legacyDisciplineId: null,
    authorSlug: 'anthropics',
    scope: 'discipline',
    primaryFieldId: 'life-sciences',
    fieldIds: ['life-sciences', 'medicine-health'],
  },
  {
    id: '7f8bca1f-1e47-4e66-94e6-7de68588b541',
    slug: 'anthropic-10x-genomics-mcp',
    legacyDisciplineId: null,
    authorSlug: 'anthropics',
    scope: 'discipline',
    primaryFieldId: 'life-sciences',
    fieldIds: ['life-sciences'],
  },
  {
    id: 'ff83c7c6-6b35-4917-ba95-82921a565456',
    slug: 'anthropic-tooluniverse-mcp',
    legacyDisciplineId: null,
    authorSlug: 'anthropics',
    scope: 'discipline',
    primaryFieldId: 'life-sciences',
    fieldIds: ['life-sciences', 'chemistry', 'medicine-health'],
  },
  {
    id: '5bee2ea1-8e4f-44c2-9a69-ccc360c5168b',
    slug: 'anthropic-medidata-mcp',
    legacyDisciplineId: null,
    authorSlug: 'anthropics',
    scope: 'discipline',
    primaryFieldId: 'medicine-health',
    fieldIds: ['medicine-health', 'life-sciences'],
  },
  {
    id: '7cc4df82-1ed4-45ae-b425-b18e26b057be',
    slug: 'anthropic-cortellis-mcp',
    legacyDisciplineId: null,
    authorSlug: 'anthropics',
    scope: 'discipline',
    primaryFieldId: 'medicine-health',
    fieldIds: ['medicine-health', 'life-sciences'],
  },
  {
    id: 'de1cad6e-0138-4f9e-bd85-0eaaf24869cd',
    slug: 'anthropic-adisinsight-mcp',
    legacyDisciplineId: null,
    authorSlug: 'anthropics',
    scope: 'discipline',
    primaryFieldId: 'medicine-health',
    fieldIds: ['medicine-health', 'life-sciences'],
  },
  {
    id: 'c7f2ba16-8221-432f-b1ff-66aa11b4c375',
    slug: 'anthropic-bio-research',
    legacyDisciplineId: null,
    authorSlug: 'anthropics',
    scope: 'discipline',
    primaryFieldId: 'life-sciences',
    fieldIds: ['life-sciences', 'medicine-health', 'chemistry'],
  },
  {
    id: '21712107-4035-437e-a5ab-7b7b01f13bc1',
    slug: 'sciatlas-literature-review',
    legacyDisciplineId: null,
    authorSlug: 'zjunlp',
    scope: 'general',
    primaryFieldId: null,
    fieldIds: [],
  },
  {
    id: 'fd378a89-0cca-4709-8f57-1f06cf4d769b',
    slug: 'sciatlas-quick-paper-search',
    legacyDisciplineId: null,
    authorSlug: 'zjunlp',
    scope: 'general',
    primaryFieldId: null,
    fieldIds: [],
  },
  {
    id: '0aa4779f-e8d6-449b-9f02-d7a6319eddde',
    slug: 'sciatlas-idea-evaluate',
    legacyDisciplineId: null,
    authorSlug: 'zjunlp',
    scope: 'general',
    primaryFieldId: null,
    fieldIds: [],
  },
  {
    id: 'b1cd0490-645e-437c-9767-eaa59ca557cb',
    slug: 'sciatlas-idea-generate',
    legacyDisciplineId: null,
    authorSlug: 'zjunlp',
    scope: 'general',
    primaryFieldId: null,
    fieldIds: [],
  },
  {
    id: '8084e0c4-807b-4f09-b68d-c4946590d233',
    slug: 'sciatlas-trend-report',
    legacyDisciplineId: null,
    authorSlug: 'zjunlp',
    scope: 'general',
    primaryFieldId: null,
    fieldIds: [],
  },
  {
    id: '36c6bfef-77ce-4c4e-8caa-074d333109b5',
    slug: 'sciatlas-researcher-review',
    legacyDisciplineId: null,
    authorSlug: 'zjunlp',
    scope: 'general',
    primaryFieldId: null,
    fieldIds: [],
  },
  {
    id: 'd58671b8-6042-47fe-b84a-61b07a969df4',
    slug: 'research-paper-review',
    legacyDisciplineId: null,
    authorSlug: 'besser-pearl',
    scope: 'general',
    primaryFieldId: null,
    fieldIds: [],
  },
  {
    id: '9bad1822-656e-4986-9397-346fe2dc69ea',
    slug: 'bio-single-cell-batch-integration',
    legacyDisciplineId: null,
    authorSlug: 'gptomics',
    scope: 'discipline',
    primaryFieldId: 'life-sciences',
    fieldIds: ['life-sciences', 'medicine-health'],
  },
  {
    id: '01f2da43-cab3-47ec-86dd-d6669721c432',
    slug: 'bio-admet-prediction',
    legacyDisciplineId: null,
    authorSlug: 'gptomics',
    scope: 'discipline',
    primaryFieldId: 'chemistry',
    fieldIds: ['chemistry', 'medicine-health'],
  },
  {
    id: 'a5b85a5a-07c5-4039-a0a2-cc0eef01fa3f',
    slug: 'sib-expasy-sparql-llm',
    legacyDisciplineId: null,
    authorSlug: 'sib-swiss',
    scope: 'discipline',
    primaryFieldId: 'life-sciences',
    fieldIds: ['life-sciences', 'medicine-health', 'chemistry'],
  },
  {
    id: 'be2ee8c2-6c24-45c2-a246-39b63f4af95d',
    slug: 'nasa-earthdata-cmr-mcp',
    legacyDisciplineId: null,
    authorSlug: 'podaac',
    scope: 'discipline',
    primaryFieldId: 'earth-environment',
    fieldIds: ['earth-environment', 'physics-astronomy'],
  },
  {
    id: 'c1de9a4a-2aa3-483f-b72c-f28377d2e2cb',
    slug: 'mcp-science-materials-project',
    legacyDisciplineId: null,
    authorSlug: 'pathintegral-institute',
    scope: 'discipline',
    primaryFieldId: 'materials-science',
    fieldIds: ['materials-science', 'chemistry', 'physics-astronomy'],
  },
  {
    id: '3ad3a25a-7306-443b-9a4f-e40bc9a0614e',
    slug: 'cyanheads-pubmed-mcp',
    legacyDisciplineId: null,
    authorSlug: 'cyanheads',
    scope: 'discipline',
    primaryFieldId: 'medicine-health',
    fieldIds: ['medicine-health', 'life-sciences'],
  },
  {
    id: '546f7f93-9865-4b59-b82b-7294e60a31c7',
    slug: 'cyanheads-pubchem-mcp',
    legacyDisciplineId: null,
    authorSlug: 'cyanheads',
    scope: 'discipline',
    primaryFieldId: 'chemistry',
    fieldIds: ['chemistry', 'materials-science', 'medicine-health'],
  },
  {
    id: '9850ca7c-2827-4592-8ac1-a3a0330edc62',
    slug: 'cyanheads-uniprot-mcp',
    legacyDisciplineId: null,
    authorSlug: 'cyanheads',
    scope: 'discipline',
    primaryFieldId: 'life-sciences',
    fieldIds: ['life-sciences', 'medicine-health'],
  },
  {
    id: 'b192a547-eace-4f40-a51b-99e2a48d13f6',
    slug: 'cyanheads-smithsonian-mcp',
    legacyDisciplineId: null,
    authorSlug: 'cyanheads',
    scope: 'discipline',
    primaryFieldId: 'humanities',
    fieldIds: ['humanities', 'arts', 'social-sciences'],
  },
];

const AUTHOR_IDENTITIES = [
  { id: '7db626a8-9b00-4d64-9c88-1ee1c43bb19b', slug: 'satija-lab' },
  { id: '4562f2f6-5ac1-487d-9fa8-e24ecd43fe73', slug: 'teichmann-lab' },
  { id: 'f5cc20cd-af2b-4443-bb3a-fae126495ea5', slug: 'embl-genomics' },
  { id: '8f4d6c60-e079-4706-bad9-1bb3e60af373', slug: 'nygc' },
  { id: '3332a206-26ce-4db1-a750-294d2a008856', slug: 'embl-ebi' },
  { id: 'e54743f1-9949-4557-9bf8-b3cfd386a410', slug: 'scripps' },
  { id: '894f720a-89b2-44b6-923a-88a0e2a9162f', slug: 'deepmind' },
  { id: '4d161a7f-9c14-425e-b9da-8c74e1c7f9bc', slug: 'cpr-embl' },
  { id: '7b669534-24be-4fc8-ba70-440d94c34fb5', slug: 'meta-ai' },
  { id: '47c65b6e-1774-4716-b861-a03eedb04400', slug: 'huggingface' },
  { id: '41dab36b-bbd6-4097-827e-66b016cb637f', slug: 'ibm-quantum' },
  { id: 'bb4b6fdb-6915-4ba5-b6b9-8d919a30edd0', slug: 'genomoncology' },
  { id: '14ce22a5-6cab-45d7-8a59-761ae835c24a', slug: 'blazickjp' },
  { id: '69dfd870-70c0-4722-812d-506f1bdfe7f6', slug: 'anthropics' },
  { id: '998cec06-4417-4552-bff6-37fccc92b23c', slug: 'zjunlp' },
  { id: '0e406291-69ad-494e-a213-0c08caadf6e5', slug: 'besser-pearl' },
  { id: 'bb48d78a-fb1f-4027-a401-c05d57ff241a', slug: 'gptomics' },
  { id: '9f580cbd-5d7a-431c-b8d0-2cb284e69c61', slug: 'sib-swiss' },
  { id: 'fbdefe50-8558-4bbb-9047-f373e81a7f36', slug: 'podaac' },
  { id: 'b622160a-cdbf-4a85-b19c-48302c13fa38', slug: 'pathintegral-institute' },
  { id: '25d3b400-85bf-43ed-812e-3adb5f50a5c6', slug: 'cyanheads' },
];

const cloneResourceIdentity = (identity) => identity && ({
  ...identity,
  fieldIds: [...identity.fieldIds],
});

const resourcesBySlug = new Map(RESOURCE_IDENTITIES.map((identity) => [identity.slug, identity]));
const authorsBySlug = new Map(AUTHOR_IDENTITIES.map((identity) => [identity.slug, identity]));

export const listResourceIdentities = () => RESOURCE_IDENTITIES.map(cloneResourceIdentity);
export const listAuthorIdentities = () => AUTHOR_IDENTITIES.map((identity) => ({ ...identity }));
export const getResourceIdentity = (slug) => cloneResourceIdentity(resourcesBySlug.get(slug));
export const getAuthorIdentity = (slug) => {
  const identity = authorsBySlug.get(slug);
  return identity ? { ...identity } : null;
};
